Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 185, in on_message
    print(data[user]["Stats"]["StatImage"])
KeyError: 'StatImage'
